export const CREATE_USER = 'CREATE_USER';
export const EDIT_USER = 'EDIT_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const DELETE_USER = 'DELETE_USER';
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export const CREATE_USER_ROLE = 'EDIT_USER_ROLE';
export const EDIT_USER_ROLE = 'EDIT_USER_ROLE';
export const FETCH_USERS_ROLES = 'FETCH_USERS_ROLE';
export const FETCH_USER_ROLE = 'FETCH_USER_ROLE';
export const DELETE_USER_ROLE = 'DELETE_USER_ROLE';

export const CREATE_CUSTOMER ='CREATE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

export const CREATE_SUPPLIER = 'CREATE_SUPPLIER';
export const EDIT_SUPPLIER = 'EDIT_SUPPLIER';
export const FETCH_SUPPLIER = 'FETCH_SUPPLIER';
export const FETCH_SUPPLIERS = 'FETCH_SUPPLIERS';
export const DELETE_SUPPLIER = 'DELETE_SUPPLIER';

export const CREATE_RAW_MATERIAL = 'CREATE_RAW_MATERIAL';
export const EDIT_RAW_MATERIAL = 'EDIT_RAW_MATERIAL';
export const FETCH_RAW_MATERIAL = 'FETCH_RAW_MATERIAL';
export const FETCH_RAW_MATERIALS = 'FETCH_RAW_MATERIALS';
export const DELETE_RAW_MATERIAL = 'DELETE_RAW_MATERIAL';

export const CREATE_PACKING_MATERIAL = 'CREATE_PACKING_MATERIAL';
export const EDIT_PACKING_MATERIAL = 'EDIT_PACKING_MATERIAL';
export const FETCH_PACKING_MATERIAL = 'FETCH_PACKING_MATERIAL';
export const FETCH_PACKING_MATERIALS = 'FETCH_PACKING_MATERIALS';
export const DELETE_PACKING_MATERIAL = 'DELETE_PACKING_MATERIAL';

export const CREATE_SFG_MATERIAL = 'CREATE_SFG_MATERIAL';
export const EDIT_SFG_MATERIAL = 'EDIT_SFG_MATERIAL';
export const FETCH_SFG_MATERIAL = 'FETCH_SFG_MATERIAL';
export const FETCH_SFG_MATERIALS = 'FETCH_SFG_MATERIALS';
export const DELETE_SFG_MATERIAL = 'DELETE_SFG_MATERIAL';

export const CREATE_FG_MATERIAL = 'CREATE_FG_MATERIAL';
export const EDIT_FG_MATERIAL = 'EDIT_FG_MATERIAL';
export const FETCH_FG_MATERIAL = 'FETCH_FG_MATERIAL';
export const FETCH_FG_MATERIALS = 'FETCH_FG_MATERIALS';
export const DELETE_FG_MATERIAL = 'DELETE_FG_MATERIAL';

export const CREATE_PRODUCT_MASTER = 'CREATE_PRODUCT_MASTER';
export const EDIT_PRODUCT_MASTER = 'EDIT_PRODUCT_MASTER';
export const FETCH_PRODUCT_MASTER = 'FETCH_PRODUCT_MASTER';
export const FETCH_PRODUCTS_MASTER = 'FETCH_PRODUCTS_MASTER';
export const DELETE_PRODUCT_MASTER = 'DELETE_PRODUCT_MASTER';

export const CREATE_PURCHASE_ORDER_RAW = 'CREATE_PURCHASE_ORDER_RAW'; 
export const CREATE_PURCHASE_ORDER_RAW_ERROR = 'CREATE_PURCHASE_ORDER_RAW_ERROR';
export const EDIT_PURCHASE_ORDER_RAW = 'EDIT_PURCHASE_ORDER_RAW';
export const FETCH_PURCHASE_ORDER_RAW = 'FETCH_PURCHASE_ORDER_RAW';
export const FETCH_PURCHASE_ORDERS_RAW = 'FETCH_PURCHASE_ORDERS_RAW';
export const NEW_GRN_PURCHASE_ORDER_RAW = 'NEW_GRN_PURCHASE_ORDER_RAW';
export const NEW_BANK_PAYMENT_PURCHASE_ORDER_RAW = 'NEW_BANK_PAYMENT_PURCHASE_ORDER_RAW'; 
export const NEW_CASH_PAYMENT_PURCHASE_ORDER_RAW = 'NEW_CASH_PAYMENT_PURCHASE_ORDER_RAW';
export const NEW_ADDITIONAL_BANK_PAYMENT_PURCHASE_ORDER_RAW = 'NEW_ADDITIONAL_BANK_PAYMENT_PURCHASE_ORDER_RAW';
export const NEW_ADDITIONAL_CASH_PAYMENT_PURCHASE_ORDER_RAW = 'NEW_ADDITIONAL_CASH_PAYMENT_PURCHASE_ORDER_RAW';
export const DELETE_PURCHASE_ORDER_RAW = 'DELETE_PURCHASE_ORDER_RAW';
export const SEARCH_PURCHASE_ORDERS_RESULT_RAW = 'SEARCH_PURCHASE_ORDERS_RESULT_RAW';

export const CREATE_PURCHASE_ORDER_PACKING = 'CREATE_PURCHASE_ORDER_PACKING';
export const EDIT_PURCHASE_ORDER_PACKING = 'EDIT_PURCHASE_ORDER_PACKING';
export const FETCH_PURCHASE_ORDER_PACKING = 'FETCH_PURCHASE_ORDER_PACKING';
export const FETCH_PURCHASE_ORDERS_PACKING = 'FETCH_PURCHASE_ORDERS_PACKING';
export const NEW_GRN_PURCHASE_ORDER_PACKING = 'NEW_GRN_PURCHASE_ORDER_PACKING';
export const NEW_BANK_PAYMENT_PURCHASE_ORDER_PACKING = 'NEW_BANK_PAYMENT_PURCHASE_ORDER_PACKING';
export const NEW_CASH_PAYMENT_PURCHASE_ORDER_PACKING = 'NEW_CASH_PAYMENT_PURCHASE_ORDER_PACKING';
export const DELETE_PURCHASE_ORDER_PACKING = 'DELETE_PURCHASE_ORDER_PACKING';
export const SEARCH_PURCHASE_ORDERS_RESULT_PACKING = 'SEARCH_PURCHASE_ORDERS_RESULT_PACKING';

export const CREATE_INVOICE = 'CREATE_INVOICE';
export const EDIT_INVOICE = 'EDIT_INVOICE';
export const FETCH_INVOICE = 'FETCH_INVOICE';
export const FETCH_INVOICES = 'FETCH_INVOICES';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const SEARCH_INVOICES_RESULT = 'SEARCH_INVOICES_RESULT';

export const CREATE_RETURN_INVOICE = 'CREATE_RETURN_INVOICE';
export const EDIT_RETURN_INVOICE = 'EDIT_RETURN_INVOICE';
export const FETCH_RETURN_INVOICE = 'FETCH_RETURN_INVOICE';
export const FETCH_RETURN_INVOICES = 'FETCH_RETURN_INVOICES';
export const DELETE_RETURN_INVOICE = 'DELETE_RETURN_INVOICE';
export const SEARCH_RETURN_INVOICES_RESULT = 'SEARCH_RETURN_INVOICES_RESULT';
export const NO_RETURN_INVOICE = 'NO_RETURN_INVOICE';

export const CREATE_BOM = 'CREATE_BOM';
export const EDIT_BOM = 'EDIT_BOM';
export const FETCH_BOM = 'FETCH_BOM';
export const FETCH_BOMS = 'FETCH_BOMS';
export const DELETE_BOM = 'DELETE_BOM';

export const CREATE_QUOTATION = 'CREATE_QUOTATION';
export const EDIT_QUOTATION = 'EDIT_QUOTATION';
export const FETCH_QUOTATION = 'FETCH_QUOTATION';
export const FETCH_QUOTATIONS = 'FETCH_QUOTATIONS';
export const DELETE_QUOTATION = 'DELETE_QUOTATION'; 
export const SEARCH_QUOTATIONS_RESULT = 'SEARCH_QUOTATIONS_RESULT';
export const FETCH_QUOTATION_FOR_INVOICE = 'FETCH_QUOTATION_FOR_INVOICE' 
export const CREATE_QUOTATION_ERROR = 'CREATE_QUOTATION_ERROR'

export const NEW_FINISH_GOOD_INVENTORY = 'NEW_FINISH_GOOD_INVENTORY';
export const EDIT_FINISH_GOOD_INVENTORY = 'EDIT_FINISH_GOOD_INVENTORY';
export const FETCH_FINISH_GOOD_INVENTORY = 'FETCH_FINISH_GOOD_INVENTORY';
export const FETCH_FINISH_GOODS_INVENTORY = 'FETCH_FINISH_GOODS_INVENTORY';
export const DISABLE_FINISH_GOOD_INVENTORY = 'DISABLE_FINISH_GOOD_INVENTORY';
export const SEARCH_FINISH_GOODS_INVENTORY = 'SEARCH_FINISH_GOODS_INVENTORY';

export const NEW_DISTRIBUTOR = 'NEW_DISTRIBUTOR';
export const EDIT_DISTRIBUTOR = 'EDIT_DISTRIBUTOR';
export const FETCH_DISTRIBUTOR = 'FETCH_DISTRIBUTOR';
export const FETCH_DISTRIBUTORS = 'FETCH_DISTRIBUTORS';
export const DELETE_DISTRIBUTOR = 'DELETE_DISTRIBUTOR';

export const NEW_EMPLOYEE = 'NEW_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const NEW_SALARY = 'NEW_SALARY';
export const EDIT_SALARY = 'EDIT_SALARY';
export const FETCH_SALARY = 'FETCH_SALARY';
export const FETCH_SALARIES = 'FETCH_SALARIES';
export const DELETE_SALARY = 'DELETE_SALARY';
export const SEARCH_SALARIES_RESULT = 'SEARCH_SALARIES_RESULT'

export const NEW_GRN_RM_INVENTORY = 'NEW_GRN_RM_INVENTORY'; 
export const NEW_GRN_RM_INVENTORY_ERROR = 'NEW_GRN_RM_INVENTORY_ERROR';
export const FETCH_GRN_RM_INVENTORY = 'FETCH_GRN_RM_INVENTORY';
export const FETCH_GRNS_RM_INVENTORY = 'FETCH_GRNS_RM_INVENTORY';
export const SEARCH_GRN_RMS_INVENTORY = 'SEARCH_GRN_RMS_INVENTORY';
export const GRN_BY_PURCHASE_ORDER_RM = 'GRN_BY_PURCHASE_ORDER_RM';

export const NEW_GRN_PM_INVENTORY = 'NEW_GRN_PM_INVENTORY';
export const FETCH_GRN_PM_INVENTORY = 'FETCH_GRN_PM_INVENTORY';
export const FETCH_GRNS_PM_INVENTORY = 'FETCH_GRNS_PM_INVENTORY';
export const SEARCH_GRN_PMS_INVENTORY = 'SEARCH_GRN_PMS_INVENTORY';
export const GRN_BY_PURCHASE_ORDER_PM = 'GRN_BY_PURCHASE_ORDER_PM';

export const NEW_BANK_ACCOUNT_MASTER = 'NEW_BANK_ACCOUNT_MASTER';
export const FETCH_ALL_BANK_ACCOUNTS = 'FETCH_ALL_BANK_ACCOUNTS';
export const FETCH_SINGLE_BANK_ACCOUNT = 'FETCH_SINGLE_BANK_ACCOUNT';
export const EDIT_BANK_ACCOUNT = 'EDIT_BANK_ACCOUNT';
export const DELETE_BANK_ACCOUNT = 'DELETE_BANK_ACCOUNT';
