export const CREATE_USER = 'CREATE_USER';
export const EDIT_USER = 'EDIT_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const DELETE_USER = 'DELETE_USER';
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export const CREATE_USER_ROLE = 'EDIT_USER_ROLE';
export const EDIT_USER_ROLE = 'EDIT_USER_ROLE';
export const FETCH_USERS_ROLES = 'FETCH_USERS_ROLE';
export const FETCH_USER_ROLE = 'FETCH_USER_ROLE';
export const DELETE_USER_ROLE = 'DELETE_USER_ROLE';

export const CREATE_CUSTOMER ='CREATE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

export const CREATE_SUPPLIER = 'CREATE_SUPPLIER';
export const EDIT_SUPPLIER = 'EDIT_SUPPLIER';
export const FETCH_SUPPLIER = 'FETCH_SUPPLIER';
export const FETCH_SUPPLIERS = 'FETCH_SUPPLIERS';
export const DELETE_SUPPLIER = 'DELETE_SUPPLIER';

export const CREATE_RAW_MATERIAL = 'CREATE_RAW_MATERIAL';
export const EDIT_RAW_MATERIAL = 'EDIT_RAW_MATERIAL';
export const FETCH_RAW_MATERIAL = 'FETCH_RAW_MATERIAL';
export const FETCH_RAW_MATERIALS = 'FETCH_RAW_MATERIALS';
export const DELETE_RAW_MATERIAL = 'DELETE_RAW_MATERIAL';

export const CREATE_PACKING_MATERIAL = 'CREATE_PACKING_MATERIAL';
export const EDIT_PACKING_MATERIAL = 'EDIT_PACKING_MATERIAL';
export const FETCH_PACKING_MATERIAL = 'FETCH_PACKING_MATERIAL';
export const FETCH_PACKING_MATERIALS = 'FETCH_PACKING_MATERIALS';
export const DELETE_PACKING_MATERIAL = 'DELETE_PACKING_MATERIAL';

export const CREATE_SFG_MATERIAL = 'CREATE_SFG_MATERIAL';
export const EDIT_SFG_MATERIAL = 'EDIT_SFG_MATERIAL';
export const FETCH_SFG_MATERIAL = 'FETCH_SFG_MATERIAL';
export const FETCH_SFG_MATERIALS = 'FETCH_SFG_MATERIALS';
export const DELETE_SFG_MATERIAL = 'DELETE_SFG_MATERIAL';

export const CREATE_FG_MATERIAL = 'CREATE_FG_MATERIAL';
export const EDIT_FG_MATERIAL = 'EDIT_FG_MATERIAL';
export const FETCH_FG_MATERIAL = 'FETCH_FG_MATERIAL';
export const FETCH_FG_MATERIALS = 'FETCH_FG_MATERIALS';
export const DELETE_FG_MATERIAL = 'DELETE_FG_MATERIAL';

export const CREATE_PRODUCT_MASTER = 'CREATE_PRODUCT_MASTER';
export const EDIT_PRODUCT_MASTER = 'EDIT_PRODUCT_MASTER';
export const FETCH_PRODUCT_MASTER = 'FETCH_PRODUCT_MASTER';
export const FETCH_PRODUCTS_MASTER = 'FETCH_PRODUCTS_MASTER';
export const DELETE_PRODUCT_MASTER = 'DELETE_PRODUCT_MASTER';

export const CREATE_PURCHASE_ORDER = 'CREATE_FG_MATERIAL';
export const EDIT_PURCHASE_ORDER = 'EDIT_PURCHASE_ORDER';
export const FETCH_PURCHASE_ORDER = 'FETCH_PURCHASE_ORDER';
export const FETCH_PURCHASE_ORDERS = 'FETCH_PURCHASE_ORDERS';
export const DELETE_PURCHASE_ORDER = 'DELETE_PURCHASE_ORDER';

export const CREATE_INVOICE = 'CREATE_INVOICE';
export const EDIT_INVOICE = 'EDIT_INVOICE';
export const FETCH_INVOICE = 'FETCH_INVOICE';
export const FETCH_INVOICES = 'FETCH_INVOICES';
export const DELETE_INVOICE = 'DELETE_INVOICE';

export const SEARCH_PURCHASE_ORDERS_RESULT = 'SEARCH_PURCHASE_ORDERS_RESULT';
export const SEARCH_PURCHASE_ORDERS_TEXT = 'SEARCH_PURCHASE_ORDERS_TEXT';


