export const CREATE_USER = 'CREATE_USER';
export const EDIT_USER = 'EDIT_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const DELETE_USER = 'DELETE_USER';
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export const CREATE_USER_ROLE = 'EDIT_USER_ROLE';
export const EDIT_USER_ROLE = 'EDIT_USER_ROLE';
export const FETCH_USERS_ROLES = 'FETCH_USERS_ROLE';
export const FETCH_USER_ROLE = 'FETCH_USER_ROLE';
export const DELETE_USER_ROLE = 'DELETE_USER_ROLE';

export const CREATE_CUSTOMER ='CREATE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

export const CREATE_SUPPLIER = 'CREATE_SUPPLIER';
export const EDIT_SUPPLIER = 'EDIT_SUPPLIER';
export const FETCH_SUPPLIER = 'FETCH_SUPPLIER';
export const FETCH_SUPPLIERS = 'FETCH_SUPPLIERS';
export const DELETE_SUPPLIER = 'DELETE_SUPPLIER';

export const CREATE_RAW_MATERIAL = 'CREATE_RAW_MATERIAL';
export const EDIT_RAW_MATERIAL = 'EDIT_RAW_MATERIAL';
export const FETCH_RAW_MATERIAL = 'FETCH_RAW_MATERIAL';
export const FETCH_RAW_MATERIALS = 'FETCH_RAW_MATERIALS';
export const DELETE_RAW_MATERIAL = 'DELETE_RAW_MATERIAL';

